name = DPF
description = Default template for davidfugate.com.
preview = preview.png
template = dpf-layout

; Regions
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
;stylesheets[all][] = css/layouts/dpf/dpf.layout.css
